### ISSUE TITLE
Resource issue for patchbot container

### ISSUE THREAD

**Issue by embray** [sagemath/docker-images#22]
The patchbot container build reaches the end successfully, but then when trying to launch the patchbot itself results in:

```
Sage build/upgrade complete!
[2016-05-20 10:16:56] Launching patchbot 2.5.3 with SAGE_ROOT=/opt/sage
[2016-05-20 10:16:56] Getting trusted author list...
WARNING: Do not use this copy of sage while the patchbot is running.
Traceback (most recent call last):
  File "/opt/sage/local/bin/patchbot/patchbot.py", line 1354, in <module>
    main(args)
  File "/opt/sage/local/bin/patchbot/patchbot.py", line 1302, in main
    ensure_free_space(options.sage_root)
  File "/opt/sage/local/bin/patchbot/util.py", line 267, in ensure_free_space
    raise ConfigException(msg.format(free, path))
util.ConfigException: Refusing to build with less than 4G free (4037505024 bytes available on /opt/sage)
The command '/bin/sh -c sage -i patchbot && sage -patchbot --count=0' returned a non-zero code: 1
Command exited with non-zero status 1
```

So I guess I need to figure out how to make sure the container is given more space to work with.

**Comment by nthiery** [comment]
On Fri, May 20, 2016 at 03:19:05AM -0700, Erik Bray wrote:

>    So I guess I need to figure out how to make sure the container is given
>    more space to work with.

I had a look, and apparently docker allocates 10Go by default for the
disk, which can be increased by using the --storage-opt
dm.basesize=20G to the docker _daemon_:

```
    https://github.com/snitm/docker/blob/master/daemon/graphdriver/devmapper/README.md
```

But that's annoying if every patchbot user needs to reconfigure his
daemon. Maybe there is hope using the "data device" which is
mentioned there ...
